enviroment: local
database:
    driverName: postgres
    # trunk-ignore(checkov/CKV_SECRET_4)
    dsn: postgres://postgres:admin@my-db:5432/db?sslmode=disable

httpServer:
    address: app:8080
    timeout: 4s
    idleTimeout: 60s
