version: '3.9'

services:

  db:
    image: postgres:16-alpine
    container_name: my-db
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
