enviroment: local
database:
    driverName: postgres
    # trunk-ignore(checkov/CKV_SECRET_4)
    dsn: postgres://postgres:admin@my-db/db?sslmode=disable

httpServer:
    address: localhost:10001
    timeout: 4s
    idleTimeout: 60s